# Generated by Django 5.2.7 on 2025-10-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='volume_unit',
            field=models.CharField(blank=True, choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('fl_oz', 'Fluid Ounce'), ('cup', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('ml', 'Milliliter'), ('l', 'Liter')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound')], max_length=10, null=True),
        ),
    ]
