# Generated by Django 5.2.7 on 2025-10-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_ingredient_volume_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
